// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-3WGmpIN1giw-gJp46LDvEgFib1YM8vY',
    appId: '1:208377339514:web:31a30fb7b19f21cd8f65c3',
    messagingSenderId: '208377339514',
    projectId: 'kalyan-educations',
    authDomain: 'kalyan-educations.firebaseapp.com',
    storageBucket: 'kalyan-educations.appspot.com',
    measurementId: 'G-RJKFHH9TB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEi70w4FmZSBKsKoECR7s381dbYeyLz70',
    appId: '1:208377339514:android:81f6626f66dc85cf8f65c3',
    messagingSenderId: '208377339514',
    projectId: 'kalyan-educations',
    storageBucket: 'kalyan-educations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApl-ki7lGqWBHLfrVmrchCxC_S-YOJmw',
    appId: '1:208377339514:ios:8067d501ad3dac8e8f65c3',
    messagingSenderId: '208377339514',
    projectId: 'kalyan-educations',
    storageBucket: 'kalyan-educations.appspot.com',
    iosBundleId: 'com.example.kalyanEducationVideoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApl-ki7lGqWBHLfrVmrchCxC_S-YOJmw',
    appId: '1:208377339514:ios:e3cf460f14af15d48f65c3',
    messagingSenderId: '208377339514',
    projectId: 'kalyan-educations',
    storageBucket: 'kalyan-educations.appspot.com',
    iosBundleId: 'com.example.kalyanEducationVideoApp.RunnerTests',
  );
}
