// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnAG5SH5sV_JEgpK2A2PA-fI0ng_82l8',
    appId: '1:772869858461:web:2f444cdea41bbf218ba074',
    messagingSenderId: '772869858461',
    projectId: 'ganitvani2',
    authDomain: 'ganitvani2.firebaseapp.com',
    storageBucket: 'ganitvani2.appspot.com',
    measurementId: 'G-Z48L1P4PCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJz2VDDCS1EXGuoPQJtqS7lCbrdSY_6A',
    appId: '1:772869858461:android:5af9575c1c3bd97b8ba074',
    messagingSenderId: '772869858461',
    projectId: 'ganitvani2',
    storageBucket: 'ganitvani2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBUAFUB-VMa4g8dZmIRefIIVFLDdCRmA',
    appId: '1:772869858461:ios:fd43cdeb2712243a8ba074',
    messagingSenderId: '772869858461',
    projectId: 'ganitvani2',
    storageBucket: 'ganitvani2.appspot.com',
    iosBundleId: 'com.example.kalyanEducationVideoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRBUAFUB-VMa4g8dZmIRefIIVFLDdCRmA',
    appId: '1:772869858461:ios:aeaa5508136a07cc8ba074',
    messagingSenderId: '772869858461',
    projectId: 'ganitvani2',
    storageBucket: 'ganitvani2.appspot.com',
    iosBundleId: 'com.example.kalyanEducationVideoApp.RunnerTests',
  );
}
